### ISSUE TITLE
Issues for recent reorg

### ISSUE THREAD

**Issue by anngvu** [gf-dcc/docs#24]
Noticed reorg recently and observed some :

- "Analyze Data" should be under Onboarding section -- I think this doesn't quite make sense
- Should "Index" actually be called "About"?
- FAQ should always be one of the last sections rather than at the top
- What happened to the descriptions for each team (replaced by empty Awardees section)? That was really helpful.

**Comment by cconrad8** [comment]
Sorry - I've been working on this today so let's just say it's in a mess state right now - but thanks for pointing out the things to fix! Doing this ASAP!
